### ISSUE TITLE
Link to zlib-1.2.13 no longer valid

### ISSUE THREAD

**Issue by langefa** [magv/ratracer#1]
The link to get http://zlib.net/zlib-1.2.13.tar.xz now returns a 404, i.e. the file is no longer available under that link. If I interpret http://zlib.net/ correctly, links to older versions are not necessarily kept or static. Only https://zlib.net/current/zlib.tar.gz seems to be a permanent link.

**Comment by magv** [comment]
Thanks for notifying, and sorry for the wait. Yes, that link is broken now. I will update to `http://zlib.net/fossils/zlib-1.3.1.tar.gz`, which seems more stable. In general I prefer to fix the versions of the dependencies, so to avoid surprises.
